### ISSUE TITLE
Add Map Option where "Faded Sight" is only applied to lower elevation characters.

### ISSUE THREAD

**Issue by adventuremagic123** [melek/lib_elevation#12]
I have a scenario where there is a flying character, a wall, and ground level characters.  When the elevation is "ground", even though the ground level characters and flying character can't see each other because of the interposing wall -- I would still like the higher elevation character to retain vision.  However, when the elevation is "flying", I want the lower elevation characters to not have any vision.

**Comment by melek** [comment]
I've added a new Map Option called `sightFilter` to  allow filtering tokens from having their sight type changed when faded. 

Here is a rundown on values for the setting:
* `0`: Default, any tokens - Works like normal; When faded, any token can have its sight type changed based on the `fadedSightType` setting.
* `1`: Filter out tokens above current elevation - Higher tokens will be exempted from sight changes when faded. For instance, flying tokens will always have sight when at a lower token's elevation. This is really useful for estimating areas on the ground which may be obscured relative to a flying character - just because you can see OVER a tower, doesn't mean you can see ground units behind it. 
* `2`: Filter out tokens below current elevation - Lower tokens will be exempted from sight changes when faded. You might want to use this when underground, where flying creatures may not have any sight advantage over ground-level tokens, and ground level tokens might be able to see through tunnels the flying token can't access until they descend.

Slated for 1.0b6. @adventuremagic123 I've given you a preview of this change in Discord, comment here once you've tested it to confirm it works or report an issue before I close it.

**Comment by melek** [comment]
Added in 1.0b6. Appears to work :)
