### ISSUE TITLE
Please describe each of the lib tokens in your releases, their purpose, and if they are required or optional -- along with upgrade instructions.

### ISSUE THREAD

**Issue by adventuremagic123** [melek/lib_elevation#13]
It would help me a lot to know what the purpose of each lib token is in your releases, whether I need all of them or if some are optional, and upgrade instructions for going from the previous version of your release to the current version.  It would be nice to have this information in a README.txt (or whatever other name) file as part of the release.

**Comment by melek** [comment]
I feel like the release notes are clear about the demo campaign:

> The demo campaign also includes additional libraries, Lib:SimpleDoors and Lib:EventTokens, which help showcase the Elevation library - but are **entirely separate libraries not needed to use Lib:Elevation**.

I did remove the 'Update' process since it is just done by replacing the library, but adding it is no problem and can help give confidence to users. 👍 

To clarify here in case others view this issue: The Lib:Elevation token is the **only** library token that is required. The doors and event pads in the demo campaign are not part of Lib:Elevation. Updating is as simple as deleting or renaming the old version of the library and importing the new one, your map data will be fully preserved.

Will close once I have updated the release notes in the next beta version.

**Comment by melek** [comment]
In 1.07b I've clarified that the additional tokens are for showcasing and development, both in the library and the release notes. 

For those interested in using the libraries, they can read the token notes or otherwise experiment with them - they are separate projects outside the scope of what I'm documenting in this repository. For anyone wants to know more about those, ask away on Discord :)

**Comment by adventuremagic123** [comment]
Thank you.
