### ISSUE TITLE
State updates not working in some scenarios

### ISSUE THREAD

**Issue by moonbrew** [melek/lib_elevation#16]
- When creating a new elevation (say 25), and selecting `Link current elevation's tokens at their current positions` (current elevation being 20), the new linked tokens on the new elevation don't have the `isElevationToken` state.
- In my scenario, all the newly linked tokens got the `isBelow` state because they probably still had the lower default elevation values (my default elevation was 10). Moving them to the current elevation (25) did not remove the `isBelow` state. This might be an edge case as when testing with unlinked npc tokens, the issue doesn't happen

**Comment by melek** [comment]
@MoonBrew

I'm so far unable to replicate this on the demo campaign. On the Blue Water Inn map in the demo for 1.0b8 I tried:

- Going to Elevation '0' (the base elevation)
- Adding a new elevation ('40')
- Selecting 'Link current elevation's tokens at their current positions'
- Result: All elevation tokens were carried forward, retaining their `isElevationToken` state. No tokens gained the 'isBelow' state, despite each tokens' `Elevation` property was still set 0.

Can you please check if your elevation tokens had the `isElevationToken` state before copying the layer's tokens? If not, the state might not get applied in this case (which would not be a bug per se, as you may have intentionally turned off that state).

As for why your elevation token would gain the `isBelow` state, that certainly should not happen - elevation tokens should never be assigned those states automatically and are ignored for the token-fading/elevation state calculation. However, if the token has an `isBelow` state before you copied the elevation (either purposefully or due to a bug in a past version), that state would be carried forward.

Let me know if you can still replicate this bug and the steps on the demo or a blank campaign (with the 3 elevation states added) so I can test and fix if there is a bug here!

**Comment by melek** [comment]
I still have not been able to replicate this in either 1.0b8 nor 1.0rc-1 during development. If you still have the issue, let me know along with how you replicate it and a copy of the affected map so I can test it!
