### ISSUE TITLE
Adjust the location of the Elevation control panel when TheDoors is also enabled

### ISSUE THREAD

**Issue by jshank** [melek/lib_elevation#20]
If at all possible, could you check to see if TheDoors is running and adjust the location of the elevation control panel as to not overlap? 

Context - https://discord.com/channels/296230822262865920/884448977976721431/955491122749276230

**Comment by melek** [comment]
I'm working on a new release. I'm looking for a lightweight way to provide this functionality, since overlays are increasingly used and I'd like to be accommodating - would a generic option to adjust the positioning by X pixels be acceptable?

**Comment by melek** [comment]
For 1.0rc-1, I've added an optional margin for the lower-right widget and readout that is settable campaign-wide from the map the Library token is on. The option exists for PCs and GMs, since their overlay setup may be different:
![image](https://user-images.githubusercontent.com/220149/226739782-940d14a7-fd35-4ab1-900d-a4ad61696eb8.png)
