### ISSUE TITLE
Elevation selection list not working on Linux or MacOS

### ISSUE THREAD

**Issue by iuvenis** [melek/lib_elevation#7]
Both using 1.06a and the new 1.0b (haven't tried earlier) I'm finding that clicking on the selection list only grays out the elevation options but doesn't actually switch elevation state. The selection list then gets stuck in that state until I click anywhere on the map with the interaction tool. I can switch elevation via the "Pick Tkn Elevation", or arrow up/down buttons below the list, or via the macro buttons visible upon selection of the library token.

All of this holds true both when putting the library token into a new map and when loading your demo campaign. Everything else seems to be working, at least under cursory testing, so it's not a gamebreaker.

I am running Maptool v1.9.3 on Linux.
**Edit:** I just tried it on the same computer running Windows and that works fine. Would be interesting if somebody else managed to run it on Linux without this bug.
**EditEdit:** Aaand, for the sake of completeness I tried it on a different computer (MacBookPro) running Big Sur 11.4 where it does **not** work - same problem as on Linux!

I'll update the issue if it resolves itself or I find out anything new, of course.

![elevation](https://user-images.githubusercontent.com/26324215/131178599-7ad89cf1-f882-40d4-b331-f800999b4e26.gif)

**Comment by melek** [comment]
Thank you for testing this, I had trouble on my Mac and wasn't sure if it was me or not.

I suspect this is an underlying issue with MapTool/Java that I'll have to isolate and get fixed in core. I will work on this.

Edit: If this turns out to be an MT bug, I'll update the UI so it works on Mac/Linux. It is cute that it looks like the MT UI, but it really isn't required.

**Comment by melek** [comment]
Fixed by removing the 'Multiple' keyword in the overlay's `<select>` tag. Not sure why that caused the issue, but it seems to have worked so far.

@iuvenis I've released the fix in [1.0b2](https://github.com/melek/lib_elevation/releases/tag/1.0b2) - can you confirm that it works for you on MacOS and Linux? I was unable to test on Linux but it worked on my MacBook Pro.

If that is confirmed we can close this issue.

**Comment by iuvenis** [comment]
Works on Linux as well now! Thanks for the quick fix :)

**Comment by melek** [comment]
Noting that this bug has an issue in MapTool: https://github.com/RPTools/maptool/issues/2741
